# Generated by Django 3.2.5 on 2021-10-28 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SldStyle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('style_type', models.CharField(blank=True, default='simple', max_length=100)),
                ('workspace', models.CharField(blank=True, max_length=100)),
                ('attribute_name', models.CharField(blank=True, max_length=100)),
                ('number_of_class', models.IntegerField(blank=True, default=5, null=True)),
                ('color_palette', models.CharField(blank=True, default='Spectral_r', max_length=1000)),
                ('geom_type', models.CharField(blank=True, default='polygon', max_length=10)),
                ('classification_method', models.CharField(blank=True, default='natural_break', max_length=50)),
                ('fill_color', models.CharField(blank=True, default='#ffffff', max_length=20)),
                ('stroke_color', models.CharField(blank=True, default='#333333', max_length=20)),
                ('stroke_width', models.IntegerField(blank=True, default=1, null=True)),
                ('opacity', models.FloatField(blank=True, default=1, null=True)),
                ('schema', models.CharField(blank=True, default='public', max_length=100)),
                ('pg_table_name', models.CharField(blank=True, max_length=100)),
                ('point_size', models.IntegerField(blank=True, default=6, null=True)),
                ('well_known_name', models.CharField(blank=True, default='circle', max_length=20)),
                ('point_rotation', models.IntegerField(blank=True, default=0, null=True)),
                ('stroke_linecap', models.CharField(blank=True, default='round', max_length=20)),
                ('stroke_dasharray', models.CharField(blank=True, max_length=20)),
                ('perpendicular_offset', models.CharField(blank=True, max_length=20)),
                ('feature_label', models.BooleanField(blank=True, default=False)),
                ('font_family', models.CharField(blank=True, default='Aerial', max_length=100)),
                ('font_color', models.CharField(blank=True, default='#333333', max_length=20)),
                ('font_size', models.IntegerField(blank=True, default=14, null=True)),
                ('font_weight', models.CharField(blank=True, default='normal', max_length=20)),
                ('font_style', models.CharField(blank=True, default='normal', max_length=20)),
                ('halo_color', models.CharField(blank=True, default='#ffffff', max_length=20)),
                ('halo_radius', models.IntegerField(blank=True, default=1, null=True)),
                ('continuous_legend', models.BooleanField(blank=True, default=True)),
                ('raster_min_val', models.IntegerField(blank=True, null=True)),
                ('raster_max_val', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Styles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('description', models.CharField(blank=True, max_length=200)),
            ],
        ),
    ]
