# Generated by Django 3.2.5 on 2022-02-08 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('styles', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Styles',
        ),
        migrations.RemoveField(
            model_name='sldstyle',
            name='attribute_name',
        ),
        migrations.RemoveField(
            model_name='sldstyle',
            name='feature_label',
        ),
        migrations.RemoveField(
            model_name='sldstyle',
            name='fill_color',
        ),
        migrations.RemoveField(
            model_name='sldstyle',
            name='font_color',
        ),
        migrations.RemoveField(
            model_name='sldstyle',
            name='font_family',
        ),
        migrations.RemoveField(
            model_name='sldstyle',
            name='font_size',
        ),
        migrations.RemoveField(
            model_name='sldstyle',
            name='font_style',
        ),
        migrations.RemoveField(
            model_name='sldstyle',
            name='font_weight',
        ),
        migrations.RemoveField(
            model_name='sldstyle',
            name='halo_color',
        ),
        migrations.RemoveField(
            model_name='sldstyle',
            name='halo_radius',
        ),
        migrations.RemoveField(
            model_name='sldstyle',
            name='perpendicular_offset',
        ),
        migrations.RemoveField(
            model_name='sldstyle',
            name='pg_table_name',
        ),
        migrations.RemoveField(
            model_name='sldstyle',
            name='point_rotation',
        ),
        migrations.RemoveField(
            model_name='sldstyle',
            name='point_size',
        ),
        migrations.RemoveField(
            model_name='sldstyle',
            name='stroke_color',
        ),
        migrations.RemoveField(
            model_name='sldstyle',
            name='stroke_dasharray',
        ),
        migrations.RemoveField(
            model_name='sldstyle',
            name='stroke_linecap',
        ),
        migrations.RemoveField(
            model_name='sldstyle',
            name='stroke_width',
        ),
        migrations.RemoveField(
            model_name='sldstyle',
            name='style_type',
        ),
        migrations.RemoveField(
            model_name='sldstyle',
            name='well_known_name',
        ),
        migrations.AlterField(
            model_name='sldstyle',
            name='geom_type',
            field=models.CharField(blank=True, default='raster', max_length=10),
        ),
    ]
