# Generated by Django 3.2.5 on 2021-08-17 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suitability', '0002_raster_vector'),
    ]

    operations = [
        migrations.CreateModel(
            name='Boundary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=500)),
                ('file', models.FileField(blank=True, max_length=255, null=True, upload_to='boundary/')),
            ],
        ),
    ]
