# Generated by Django 3.2.5 on 2021-08-23 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suitability', '0005_suitability'),
    ]

    operations = [
        migrations.RenameField(
            model_name='suitability',
            old_name='suitability_comment',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='suitability',
            old_name='suitability_type',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='suitability',
            name='suitability',
        ),
        migrations.AddField(
            model_name='suitability',
            name='file',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to='suitability/'),
        ),
        migrations.AddField(
            model_name='suitability',
            name='file_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
