# Generated by Django 3.2.5 on 2022-02-07 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suitability', '0006_auto_20210823_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suitability',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
