# Generated by Django 3.2.5 on 2022-02-07 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suitability', '0007_alter_suitability_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Project',
        ),
        migrations.AlterField(
            model_name='boundary',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='raster',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='vector',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
