version: '3'

services:
  web:
    env_file: .env
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    volumes:
      - .:/code
    depends_on:
      - db
    ports:
      - 8000:8000
    entrypoint: sh /code/entrypoint.sh

  db:
    image: mdillon/postgis:11-alpine
    restart: always
    volumes:
      - ./postgres_data:/var/lib/postgresql/data/
    ports:
      - 5438:5432
    env_file:
      - .env

  geoserver:
    image: kartoza/geoserver:2.19.0
    container_name: geoserver-naxa
    env_file: geoserver_env.txt
    volumes:
      - ./geoserver-data:/opt/geoserver/data_dir
      - ./geoserver-data/web.xml:/usr/local/tomcat/webapps/geoserver/WEB-INF/web.xml
    ports:
      - "8080:8080"
    restart : on-failure
    depends_on:
      - db