//AUTHENTICATE and USER
export const USER_LOADING = "USER_LOADING";
export const USER_LOADED = "USER_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_ERROR = "LOGIN_ERROR";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";

//ERROR and MESSAGE
export const GET_ERRORS = "GET_ERRORS";
export const CREATE_MESSAGE = "CREATE_MESSAGE";

//AHP
export const CALCULATE_AHP = "CALCULATE_AHP";

// BBOX
export const ADD_BBOX = "ADD_BBOX";

//PROJECT
export const ADD_PROJECT = "ADD_PROJECT";
export const GET_PROJECT = "GET_PROJECT";
export const UPDATE_PROJECT = "UPDATE_PROJECT";
export const DELETE_PROJECT = "DELETE_PROJECT";

//VECTOR
export const VECTOR_LOADING = "VECTOR_LOADING";
export const ADD_VECTOR = "ADD_VECTOR";
export const GET_VECTOR = "GET_VECTOR";
export const UPDATE_VECTOR = "UPATE_VECTOR";
export const DELETE_VECTOR = "DELETE_VECTOR";

//RASTER
export const RASTER_LOADING = "RASTER_LOADING";
export const ADD_RASTER = "ADD_RASTER";
export const GET_RASTER = "GET_RASTER";
export const UPDATE_RASTER = "UPDATE_RASTER";
export const DELETE_RASTER = "DELETE_RASTER";

//BOUNDARY
export const BOUNDARY_LOADING = "BOUNDARY_LOADING";
export const ADD_BOUNDARY = "ADD_BOUNDARY";
export const GET_BOUNDARY = "GET_BOUNDARY";
export const UPDATE_BOUNDARY = "UPDATE_BOUNDARY";
export const DELETE_BOUNDARY = "DELETE_BOUNDARY";

//SUITABILITY
export const SUITABILITY_LOADING = "SUITABILITY_LOADING";
export const ADD_SUITABILITY = "ADD_SUITABILITY";
export const GET_SUITABILITY = "GET_SUITABILITY";
export const UPDATE_SUITABILITY = "UPDATE_SUITABILITY";
export const DELETE_SUITABILITY = "DELETE_SUITABILITY";

//GEOSERVER
export const GET_LAYERS = "GET_LAYERS";
export const GET_STYLES = "GET_STYLES";

//STYLE
export const GET_STYLE_NAME = "GET_STYLE_NAME";
export const GET_SLD = "GET_SLD";
export const GET_STYLE = "GET_STYLE";
export const PATCH_STYLE = "PATCH_STYLE";
export const ADD_STYLE = "ADD_STYLE";
export const DELETE_STYLE = "DELETE_STYLE";
export const UPDATE_STYLE = "UPDATE_STYLE";

//Data Preparation
export const CLIP_VECTOR = "CLIP_VECTOR";
export const CLIP_RASTER = "CLIP_RASTER";
export const MERGE_VECTORS = "MERGE_VECTORS";
export const BUFFER_VECTOR = "BUFFER_VECTOR";
export const RASTER_TO_VECTOR = "RASTER_TO_VECTOR";
export const VECTOR_TO_RASTER = "VECTOR_TO_RASTER";
export const VECTOR_TO_SHAPEFILE = "VECTOR_TO_SHAPEFILE";
export const SHAPEFILE_TO_GEOJSON = "SHAPEFILE_TO_GEOJSON";